[package]
name = "sketches"

[workspace.package]
version = "0.1.2"
edition = "2024"
name = "sketches"

[workspace]
members = [
    "crates/cpc",
    "crates/hll",
    "crates/theta",
    "py-sketches",
]

