[package]
name = "sketches"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/cpc",
    "crates/hll",
    "crates/theta",
    "py-sketches",
]

[dependencies]
csv = "1"
cpc = { path = "crates/cpc" }
hll = { path = "crates/hll" }
theta = { path = "crates/theta" }
