[package]
name = "sketches"
version = "0.1.4"
edition = "2024"

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }

[dev-dependencies]
csv = "1"
tracing = "0.1"
tracing-subscriber = "0.3"


[lib]
name = "sketches"
crate-type = ["cdylib", "rlib"]
