[package]
name = "rusty-sketches"
version = "0.1.1"
edition = "2021"

[lib]
name = "sketches"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
cpc = { path = "../crates/cpc" }
hll = { path = "../crates/hll" }
theta = { path = "../crates/theta" }

